language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - packages/core/node_modules
    - packages/cli/node_modules
    - packages/iam/node_modules
    - packages/lambda/node_modules
    - packages/api-gateway/node_modules
    - packages/cors/node_modules
install:
  - bash travis-install.sh
# Matrix begin
node_js:
  - "6"
env:
  - TEST_SUITE=integration
  - TEST_SUITE=core
  - TEST_SUITE=cli
  - TEST_SUITE=iam
  - TEST_SUITE=lambda
  - TEST_SUITE=api-gateway
  - TEST_SUITE=cors
# Matrix end
script:
  - bash travis-run.sh
